export const qA = [
  ["What year was the very first model of the iPhone released?", "2007"],
  ["What is the name of the man who launched eBay?", "Pierre Omidyar"],
  ["What year did eBay launch?", "1995"],
  [
    "What year did Marie Curie become the first woman to win a Nobel Prize? ",
    "1903",
  ],
  ["Which planet is the hottest in our solar system?", "Venus"],
  ["What part of the atom has no electric charge?", "Neutron"],
  ["Which planet has the most gravity?", "Jupiter"],
  [
    "Which Avenger is the only one who could calm the Hulk down?",
    "Black Widow",
  ],
  ["What is the name of Batman's butler?", "Alfred"],
  ["What does DC stand for?", "Detective Comics"],
  ["How many films did Sean Connery play James Bond in?", "7"],
  ["In what year was the first episode of South Park aired?", "1997"],
  ["How many NBA Championships did Michael Jordan win?", "6"],
  ["In what year was Broadway established?", "1750"],
  ["Which animal can be seen on the Porsche logo?", "Horse"],
  ["In what year was the first-ever Wimbledon Championship held? ", "1877"],
  [
    "Which hockey team did Wayne Gretzky play for in the '80s? ",
    "Edmonton Oilers",
  ],
  ["What is the common name for dried plums?", "Prunes"],
  ["What's the primary ingredient in hummus? ", "Chickpeas"],
  ["Which country produces the most coffee in the world? ", "Brazil"],
  ["Which city in India would you find the Taj Mahal in? ", "Agra"],
  [
    "The American designer born in 1939 as Ralph Lifshitz is better known as what?",
    " Ralph Lauren",
  ],
  ["When was the company Nike founded? ", "1971"],
  ["What animal is on Levi's logo?", "Horse"],
  ["Who designed the Sydney Opera House?", "Jorn Utzon"],
  ["How many homicides did Ted Bundy admit to?", "30"],
  ["Unabomber Ted Kaczynski was a graduate of which university?", "Harvard"],
  ["How long is the gestation period of an African elephant?", "22 months"],
  ["How many eyes does a bee have?", "5"],
  ["What is a female donkey called? ", "Jenny"],
  ["How many hearts does an octopus have?", "3"],
];
